# Generated by Django 3.1.13 on 2022-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Lastname')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='Id Number')),
                ('pic', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('next_of_kin', models.CharField(max_length=50, verbose_name='Next of Kin')),
                ('nxtofkin_relationship', models.CharField(max_length=50, verbose_name='Relationship to Nextof Kin')),
                ('nxtofkin_pic', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
